version: '3.9'

services:

  db:
    container_name: postgresql
    image: postgres:latest
    restart: unless-stopped
    networks:
      - infimetrics
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - infimetrics
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

volumes:
    pgdata:
      driver: local
    cache:
      driver: local

networks:
  infimetrics:
