version: '3.9'

services:

  db:
    container_name: postgresql
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    env_file:
      - .env

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped

    ports:
      - "9090:8080"

volumes:
    pgdata:
        driver: int
